version: '2'

services:

  nginx:
    
    build: ./nginx
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4

    ports:
      - "80:80"

  backend1:

    build: ./backend1
    environment:
      - PORT=8001 
    ports:
      - "8001:8001"       
    

  backend2:
    build: ./backend2
    environment:
      - PORT=8002
    ports:
      - "8002:8002"    

  backend3:
    build: ./backend3
    environment:
      - PORT=8003 
    ports:
      - "8003:8003"        

  backend4:
    build: ./backend4
    environment:
      - PORT=8004 
    ports:
      - "8004:8004"        

  

  
