version: '3'

services:

  nginx:
    
    build: ./nginx
    depends_on:
      - frontend1
      - frontend2
      - frontend3
      - frontend4      
      - backend1
      - backend2
      - backend3
      - backend4

    ports:
      - "80:80"

  frontend1:
    build: ./frontend1

    ports:
      - "5001:5001"


  frontend2:
    build: ./frontend2

    ports:
      - "5002:5002"

  frontend3:
    build: ./frontend3

    ports:
      - "5003:5003"

  frontend4:
    build: ./frontend4

    ports:
      - "5004:5004"


  backend1:

    build: ./backend1
     
           
    

  backend2:
    build: ./backend2
    
        

  backend3:
    build: ./backend3
    
            

  backend4:
    build: ./backend4
    
    


  

  
