services: 
  nginx:
    container_name: nginx
    
    build: ./nginx
    depends_on:
      - f1
      - frontend2
      - frontend3
      - frontend4      

    ports:
      - "80:80"
    
       
    
    

  frontend2:
    build: ./frontend2
    container_name: frontend2
    ports:
      - "5002:80"


  frontend3:
    build: ./frontend3
    container_name: frontend3
  
    ports:
      - "5003:80"

  frontend4:
    build: ./frontend4
    ports:
      - "5004:80"    
    container_name: frontend4    

  f1:
    build: ./f1
    container_name: f1

    ports: 
      - "5008:80"
        
  

  
